app/apps/data/cabinets/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = "cabinets"

urlpatterns = [
    path(
        "<slug:country>/<slug:cabinet_date>/",
        views.cabinet_detail_view,
        name="detail",
    ),
    path(
        "<slug:country>/",
        views.cabinet_list_view,
        name="list",
    ),
    path(
        "",
        RedirectView.as_view(pattern_name="country_list"),
        name="index_redirect",
    ),
]

app/apps/data/elections/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = "elections"

urlpatterns = [
    path(
        "<slug:country>/<slug:election_date>-ep/",
        views.election_detail_view,
        kwargs={"ep": True},
        name="detail_ep",
    ),
    path(
        "<slug:country>/<slug:election_date>/",
        views.election_detail_view,
        name="detail",
    ),
    path(
        "<slug:country>/",
        views.election_list_view,
        name="list",
    ),
    path(
        "",
        RedirectView.as_view(pattern_name="country_list"),
        name="index_redirect",
    ),
]

app/apps/data/parties/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = "parties"

urlpatterns = [
    path(
        "<slug:country>/<int:party_id>/",
        views.party_detail_view,
        name="detail",
    ),
    path(
        "<slug:country>/",
        views.party_list_view,
        name="list",
    ),
    path(
        "",
        RedirectView.as_view(pattern_name="country_list"),
        name="index_redirect",
    ),
]

app/apps/urls.py
"""URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/stable/topics/http/urls/
"""

from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from .base import views as views_base
from .data.core import views as views_core
from .views_data import views as views_data

urlpatterns = [
    # Data urls
    path("data/parties/", include("apps.data.parties.urls")),
    path("data/elections/", include("apps.data.elections.urls")),
    path("data/cabinets/", include("apps.data.cabinets.urls")),
    path("data/", views_core.data_index_view, name="country_list"),
    # CSV tables
    path("data-csv/<slug:db_table>/", views_data.csv_view, name="data_csv"),
    # Documentation urls
    path("docs/", include("apps.docs.urls")),
    # API urls
    path("api/v1/", include("apps.api.urls")),
    # path("api-auth/", include("rest_framework.urls")),
    # Page urls
    path("", include("apps.pages.urls")),
    # Misc urls
    path("clear-cache", views_base.clear_cache, name="clear_cache"),
    # Admin urls
    path("admin-parlgov/doc/", include("django.contrib.admindocs.urls")),
    path("admin-parlgov/", admin.site.urls),
]

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

app/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}parties, elections, cabinets{% endblock %}

{% block content %}
  <h1>ParlGov project</h1>
  <div class="row">
    <div class="col-md">
      {% include 'home/home_project-description.html' %}
    </div>
    <div class="col-md">{% include 'home/home_carousel.html' %}</div>
  </div>
{% endblock %}

app/templates/home/home_carousel.html
{% load static %}

<div
  id="carouselExampleIndicators"
  class="carousel slide"
  data-bs-ride="carousel"
>
  <div class="carousel-indicators">
    <button
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide-to="0"
      class="active"
      aria-current="true"
      aria-label="Slide 1"
    >
    </button>
    <button
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide-to="1"
      aria-label="Slide 2"
    >
    </button>
    <button
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide-to="2"
      aria-label="Slide 3"
    >
    </button>
    <button
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide-to="3"
      aria-label="Slide 4"
    >
    </button>
    <button
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide-to="4"
      aria-label="Slide 5"
    >
    </button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img
        src="{% static 'images/parliaments/germany.jpg' %}"
        class="d-block w-100"
        alt="Bundestag"
      />
    </div>
    <div class="carousel-item">
      <img
        src="{% static 'images/parliaments/sweden.jpg' %}"
        class="d-block w-100"
        alt="Riksdag"
      />
    </div>
    <div class="carousel-item">
      <img
        src="{% static 'images/parliaments/scotland.jpg' %}"
        class="d-block w-100"
        alt="Pàrlamaid na h-Alba"
      />
    </div>
    <div class="carousel-item">
      <img
        src="{% static 'images/parliaments/netherlands.jpg' %}"
        class="d-block w-100"
        alt="Tweede Kamer"
      />
    </div>
    <div class="carousel-item">
      <img
        src="{% static 'images/parliaments/european-union.jpg' %}"
        class="d-block w-100"
        alt="European Parliament"
      />
    </div>
  </div>
  <button
    class="carousel-control-prev"
    type="button"
    data-bs-target="#carouselExampleIndicators"
    data-bs-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button
    class="carousel-control-next"
    type="button"
    data-bs-target="#carouselExampleIndicators"
    data-bs-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/templates/home/home_project-description.html
{% load format_data %}

<p>
  The Parliaments and Governments Database (ParlGov) is a data infrastructure
  with information about EU and OECD democracies (1900–2023).
  <em>{{ count.Party|round_100 }} parties</em>,
  <em>{{ count.Election|round_100 }} elections</em>
  ({{ count.ElectionResult|round_100 }} results), and
  <em>{{ count.Cabinet|round_100 }} cabinets</em>
  ({{ count.CabinetParty|round_100 }} parties).
</p>

<div class="col-6  mb-4">
  <select id="country-select" class="form-select" onchange="location = this.value;">
    {% for country in countries %}
      <option value="/data/parties/{{ country.name_short|lower }}">
        {{ country.name }}
      </option>
    {% endfor %}
  </select>
</div>

<h5><i class="bi bi-globe"></i> · Examples</h5>
<dl class="row">
  <dt class="col-sm-3">Parties</dt>
  <dd class="col-sm-9">
    <i class="bi bi-people"></i> ·
    <a href="{% url 'parties:detail' 'deu' 558 %}">Social Democratic Party</a>
    — 🇩🇪 · Germany
  </dd>
  <dt class="col-sm-3">Elections</dt>
  <dd class="col-sm-9">
    <i class="bi bi-box-seam"></i> ·
    <a href="{% url 'elections:detail' 'bgr' '2014-10-05' %}">National 2014</a>
    (<a href="{% url 'elections:detail_ep' 'bgr' '2014-05-25' %}">EP</a>)
    — 🇧🇬 · Bulgaria
  </dd>
  <dt class="col-sm-3">Cabinets</dt>
  <dd class="col-sm-9">
    <i class="bi bi-briefcase"></i> ·
    <a href="{% url 'cabinets:detail' 'fin' '1917-11-27' %}">
      Svinhufvud I – 1917
    </a>
    — 🇫🇮 · Finland
  </dd>
</dl>

<h5><i class="bi bi-download"></i> · Data tables</h5>
<p>
  <i class="bi bi-people"></i> ·
  <a href="{% url 'data_csv' 'view_party' %}">Parties</a> —
  <i class="bi bi-box-seam"></i> ·
  <a href="{% url 'data_csv' 'view_election' %}">Elections</a> —
  <i class="bi bi-briefcase"></i> ·
  <a href="{% url 'data_csv' 'view_cabinet' %}">Cabinets</a>
</p>

<p>
  <strong>References</strong>
  <ul class="list-unstyled">
    <li class="mb-2">
      Döring, Holger, and Philip Manow. 2024. "ParlGov 2024 Release." Harvard
      Dataverse. — DOI: <a href="https://doi.org/10.7910/dvn/2vz5zc" target="_blank">10.7910/dvn/2vz5zc</a>
    </li>
    <li class="mb-2">
      Döring, Holger. 2025. "Advancing Data Infrastructures on Democratic
      Representation: An Open-Source Version of ParlGov." SOCIUM SFB 1342 Working
      Papers. — DOI: <a href="https://doi.org/10.26092/elib/4362" target="_blank">10.26092/elib/4362</a>
    </li>
  </ul>
</p>