app/apps/data/cabinets/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = "cabinets"

urlpatterns = [
    path(
        "<slug:country>/<slug:cabinet_date>/",
        views.cabinet_detail_view,
        name="detail",
    ),
    path(
        "<slug:country>/",
        views.cabinet_list_view,
        name="list",
    ),
    path(
        "",
        RedirectView.as_view(pattern_name="country_list"),
        name="index_redirect",
    ),
]

app/apps/data/elections/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = "elections"

urlpatterns = [
    path(
        "<slug:country>/<slug:election_date>-ep/",
        views.election_detail_view,
        kwargs={"ep": True},
        name="detail_ep",
    ),
    path(
        "<slug:country>/<slug:election_date>/",
        views.election_detail_view,
        name="detail",
    ),
    path(
        "<slug:country>/",
        views.election_list_view,
        name="list",
    ),
    path(
        "",
        RedirectView.as_view(pattern_name="country_list"),
        name="index_redirect",
    ),
]

app/apps/data/parties/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = "parties"

urlpatterns = [
    path(
        "<slug:country>/<int:party_id>/",
        views.party_detail_view,
        name="detail",
    ),
    path(
        "<slug:country>/",
        views.party_list_view,
        name="list",
    ),
    path(
        "",
        RedirectView.as_view(pattern_name="country_list"),
        name="index_redirect",
    ),
]

app/apps/docs/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = "docs"

urlpatterns = [
    path(
        "codebook/",
        views.codebook_view,
        name="codebook",
    ),
    path(
        "codebook-markdown/",
        views.codebook_markdown_view,
        name="codebook_markdown",
    ),
    path(
        "news/",
        views.NewsListView.as_view(),
        name="news",
    ),
    path(
        "",
        RedirectView.as_view(pattern_name="docs:codebook"),
        name="index",
    ),
]

app/apps/urls.py
"""URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/stable/topics/http/urls/
"""

from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from .base import views as views_base
from .data.core import views as views_core
from .views_data import views as views_data

urlpatterns = [
    # Data urls
    path("data/parties/", include("apps.data.parties.urls")),
    path("data/elections/", include("apps.data.elections.urls")),
    path("data/cabinets/", include("apps.data.cabinets.urls")),
    path("data/", views_core.data_index_view, name="country_list"),
    # CSV tables
    path("data-csv/<slug:db_table>/", views_data.csv_view, name="data_csv"),
    # Documentation urls
    path("docs/", include("apps.docs.urls")),
    # API urls
    path("api/v1/", include("apps.api.urls")),
    # path("api-auth/", include("rest_framework.urls")),
    # Page urls
    path("", include("apps.pages.urls")),
    # Misc urls
    path("clear-cache", views_base.clear_cache, name="clear_cache"),
    # Admin urls
    path("admin-parlgov/doc/", include("django.contrib.admindocs.urls")),
    path("admin-parlgov/", admin.site.urls),
]

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

app/apps/data/cabinets/models.py
from django.db import models
from django.urls import reverse

from ...base.models import (
    BaseModel,
    comment_help_text,
    data_json_help_text,
    description_help_text,
)
from ..core.helptext import data_source_help_text
from ..core.validators import validate_ascii
from ..elections.models import Election
from . import validation


class Cabinet(BaseModel):
    """Cabinet information."""

    country = models.ForeignKey("datacore.Country", on_delete=models.PROTECT)
    name = models.CharField(db_index=True, max_length=50, validators=[validate_ascii])
    start_date = models.DateField(db_index=True)
    termination_date = models.DateField(null=True, blank=True)
    caretaker = models.BooleanField(default=False)
    election = models.ForeignKey(
        "elections.Election",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        help_text="previous election — value is added or updated on save",
    )
    wikipedia = models.URLField(null=True, blank=True, max_length=200)
    data_source = models.CharField(
        blank=True, max_length=200, help_text=data_source_help_text
    )
    description = models.TextField(blank=True, help_text=description_help_text)
    comment = models.TextField(blank=True, help_text=comment_help_text)
    data_json = models.JSONField(
        default=dict, blank=True, help_text=data_json_help_text
    )

    def get_election(self):
        """Get the previous election.

        The method is used in 'self.save()' to set the 'self.election' attribute.
        """
        return Election.get_by_date(self.country, self.start_date)

    def get_absolute_url(self):
        """Get url for cabinet object)."""
        url_parameters = {"country": self.country.slug, "cabinet_date": self.start_date}
        return reverse("cabinets:detail", kwargs=url_parameters)

    def save(self, *args, **kwargs):
        """Save cabinet model and set values."""
        if self.election != self.get_election():
            self.election = self.get_election()

        super().save(*args, **kwargs)

    class Meta:
        db_table = "data_cabinet"
        ordering = ("country", "start_date")
        constraints = [
            models.UniqueConstraint(
                fields=["country", "name"],
                name="unique_cabinet_name_per_country",
            ),
            models.UniqueConstraint(
                fields=["country", "start_date"],
                name="unique_cabinet_date_per_country",
            ),
            models.CheckConstraint(
                condition=models.Q(start_date__lte=models.F("termination_date")),
                name="cabinet_start_date_smaller_than_termination_date",
            ),
        ]

    def __str__(self):
        country = self.country.name_short.capitalize()
        return f"Cabinet {country} – {self.start_date.year} {self.name} ({self.id})"


class CabinetParty(BaseModel):
    """Cabinet membership of party."""

    cabinet = models.ForeignKey(
        Cabinet,
        on_delete=models.CASCADE,
    )
    party = models.ForeignKey(
        "parties.Party",
        on_delete=models.PROTECT,
    )
    pm = models.BooleanField(default=False)
    defector = models.BooleanField(
        default=False,
        help_text=(
            "Add information in description field why party defected from cabinet"
        ),
    )
    party_id_source = models.CharField(blank=True, max_length=200)
    data_source = models.CharField(
        blank=True, max_length=200, help_text=data_source_help_text
    )
    description = models.TextField(blank=True, help_text=description_help_text)
    comment = models.TextField(blank=True, help_text=comment_help_text)
    data_json = models.JSONField(
        default=dict, blank=True, help_text=data_json_help_text
    )

    def clean(self):
        """Validation methods data before save."""
        validation.check_cabinet_party_countries(self)
        validation.check_cabinet_party_no_second_pm(self)

        return super().clean()  # pragma: no cover

    def get_absolute_url(self):
        """Get url for cabinet object."""
        return self.cabinet.get_absolute_url()

    class Meta:
        db_table = "data_cabinet_party"
        ordering = ("cabinet", "-pm")
        constraints = [
            models.UniqueConstraint(
                fields=["cabinet", "party"],
                name="unique_cabinet_party",
            ),
        ]

    def __str__(self):
        country = self.cabinet.country.name_short.capitalize()
        year = self.cabinet.start_date.year
        party = self.party.name_short

        return f"Cabinet party {country} – {year} {party} ({self.id})"

app/apps/data/elections/models.py
from decimal import Decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse

from ...base.models import (
    BaseModel,
    comment_help_text,
    data_json_help_text,
    description_help_text,
)
from ..core.helptext import data_source_help_text
from . import validation


class Election(BaseModel):
    """Election information."""

    type = models.ForeignKey(
        "datacore.Code",
        db_column="type_id",
        default=13,
        limit_choices_to={"table_variable": "election_type"},
        on_delete=models.PROTECT,
    )
    country = models.ForeignKey("datacore.Country", on_delete=models.PROTECT)
    date = models.DateField(db_index=True)
    early = models.BooleanField(default=False)
    wikipedia = models.URLField(null=True, blank=True, max_length=200)
    dissolution_date = models.DateField(null=True, blank=True)
    seats_total = models.PositiveIntegerField(validators=[MaxValueValidator(1000)])
    electorate = models.PositiveIntegerField(null=True, blank=True)
    votes_cast = models.PositiveIntegerField(null=True, blank=True)
    votes_valid = models.PositiveIntegerField(null=True, blank=True)
    data_source = models.CharField(
        blank=True, max_length=200, help_text=data_source_help_text
    )
    description = models.TextField(blank=True, help_text=description_help_text)
    comment = models.TextField(blank=True, help_text=comment_help_text)
    data_json = models.JSONField(
        default=dict, blank=True, help_text=data_json_help_text
    )

    def get_absolute_url(self):
        """Get url for election object (parliament and EP)."""
        url_parameters = {"country": self.country.slug, "election_date": self.date}

        parliament = self.type.short == "parliament"
        election_view_name = "elections:detail" if parliament else "elections:detail_ep"

        return reverse(election_view_name, kwargs=url_parameters)

    @classmethod
    def get_by_date(cls, country, date, type_short="parliament"):
        """Get the election for a date (previous or same date)."""
        election = cls.objects.filter(
            country=country, date__lte=date, type__short=type_short
        )
        return election.last()

    class Meta:
        db_table = "data_election"
        ordering = ("country", "type", "date")
        constraints = [
            models.UniqueConstraint(
                fields=["country", "date", "type"],
                name="unique_election_country_date_election_type",
            ),
        ]

    def __str__(self):
        country = self.country.name_short.capitalize()
        ep_election = "EP " if self.type.short == "ep" else ""
        return f"Election {country} – {self.date.year} {ep_election}({self.id})"


class ElectionResult(BaseModel):
    """Election result for a party."""

    election = models.ForeignKey(
        Election,
        on_delete=models.CASCADE,
    )
    party = models.ForeignKey(
        "parties.Party",
        on_delete=models.PROTECT,
    )
    party_id_source = models.CharField(blank=True, max_length=200)
    alliance = models.ForeignKey(
        "self",
        related_name="alliance_set",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        help_text=(
            "'election_result_id' of electoral alliance "
            "party belongs to in this election"
        ),
    )
    seats = models.PositiveIntegerField(
        null=True,
        blank=True,
        db_index=True,
        validators=[MaxValueValidator(1000)],
        help_text=(
            "enter '0' if the party won no seats -- "
            "leave empty for alliances were seats are coded for members"
        ),
    )
    vote_share = models.DecimalField(
        max_digits=5,
        decimal_places=2,  # not used in SQLite, see 'save()' method
        null=True,
        blank=True,
        validators=[
            MinValueValidator(Decimal(0)),
            MaxValueValidator(Decimal(100)),
        ],
        help_text=("official vote share -- max. two  decimal places"),
    )
    votes = models.PositiveIntegerField(null=True, blank=True)
    data_source = models.CharField(
        blank=True, max_length=200, help_text=data_source_help_text
    )
    description = models.TextField(blank=True, help_text=description_help_text)
    comment = models.TextField(blank=True, help_text=comment_help_text)
    data_json = models.JSONField(
        default=dict, blank=True, help_text=data_json_help_text
    )

    @property
    def seat_share(self):
        """Provide seat share as class property."""
        if self.seats and self.election.seats_total:
            return float(self.seats) / float(self.election.seats_total) * 100.0

    def clean(self):
        """Validate data on safe."""
        validation.check_election_party_countries(self)
        if self.alliance:
            validation.check_alliance_no_self_reference(self)
            validation.check_alliance_election_ids_equal(self)

        return super().clean()

    def save(self, *args, **kwargs):
        """Ensure vote_share is properly rounded to field's decimal_places."""
        if self.vote_share is not None:
            if not isinstance(self.vote_share, Decimal):
                self.vote_share = Decimal(str(self.vote_share))

            field = self._meta.get_field("vote_share")
            quantize_pattern = Decimal("0." + "0" * field.decimal_places)

            self.vote_share = self.vote_share.quantize(quantize_pattern)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Get url for election result object (parliament and EP)."""
        return self.election.get_absolute_url()

    class Meta:
        db_table = "data_election_result"
        ordering = ("election", "-seats", "-vote_share")
        constraints = [
            models.UniqueConstraint(
                fields=["election", "party"],
                name="unique_election_result_party",
            ),
        ]

    def __str__(self):
        country = self.election.country.name_short.capitalize()
        year = self.election.date.year
        ep_election = "EP " if self.election.type.short == "ep" else ""
        party = self.party.name_short

        return f"Election result {country} – {year} {ep_election}{party} ({self.id})"

app/apps/data/cabinets/views.py
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse

from ..core.utils import get_country_or_404, previous_next_object
from .models import Cabinet, CabinetParty


def cabinet_detail_view(request, country: str, cabinet_date: str):
    """Details of cabinet page."""
    cabinet = get_object_or_404(
        Cabinet, country__name_short=country.upper(), start_date=cabinet_date
    )
    parties = CabinetParty.objects.filter(cabinet=cabinet).select_related(
        "party__country"
    )

    context = {
        "cabinet": cabinet,
        "parties": parties,
        "previous_next": previous_next_object(cabinet),
    }

    return TemplateResponse(request, "data/cabinet-detail.html", context)


def cabinet_list_view(request, country: str):
    """List cabinets filtered by country short."""
    context = {"country": get_country_or_404(country)}
    context["cabinet_list"] = (
        Cabinet.objects.select_related("country")
        .prefetch_related("cabinetparty_set__party__country")
        .filter(country=context["country"])
        .order_by("-start_date")
    )

    return TemplateResponse(request, "data/cabinet-list.html", context)

app/apps/data/core/views.py
from django.template.response import TemplateResponse

from ...views_data.views import get_public_db_tables
from .models import Country


def data_index_view(request):
    """Index page of data with countries and tables links."""
    context = {
        "countries": Country.objects.all(),
        "tables": get_public_db_tables(),
    }

    return TemplateResponse(request, "data/data-index.html", context)

app/templates/data/_include_form-select-country.html
<hr />

<ul class="nav">
  <li>
    {# hard coded to avoid database queries #}
    <select id="country-select" class="form-select" onchange="location = this.value;">
      <option {% if country == "aus" %} selected {% else %} value="{{ url }}aus/" {% endif %}>Australia</option>
      <option {% if country == "aut" %} selected {% else %} value="{{ url }}aut/" {% endif %}>Austria</option>
      <option {% if country == "bel" %} selected {% else %} value="{{ url }}bel/" {% endif %}>Belgium</option>
      <option {% if country == "bgr" %} selected {% else %} value="{{ url }}bgr/" {% endif %}>Bulgaria</option>
      <option {% if country == "can" %} selected {% else %} value="{{ url }}can/" {% endif %}>Canada</option>
      <option {% if country == "hrv" %} selected {% else %} value="{{ url }}hrv/" {% endif %}>Croatia</option>
      <option {% if country == "cyp" %} selected {% else %} value="{{ url }}cyp/" {% endif %}>Cyprus</option>
      <option {% if country == "cze" %} selected {% else %} value="{{ url }}cze/" {% endif %}>Czech Republic</option>
      <option {% if country == "dnk" %} selected {% else %} value="{{ url }}dnk/" {% endif %}>Denmark</option>
      <option {% if country == "est" %} selected {% else %} value="{{ url }}est/" {% endif %}>Estonia</option>
      <option {% if country == "fin" %} selected {% else %} value="{{ url }}fin/" {% endif %}>Finland</option>
      <option {% if country == "fra" %} selected {% else %} value="{{ url }}fra/" {% endif %}>France</option>
      <option {% if country == "deu" %} selected {% else %} value="{{ url }}deu/" {% endif %}>Germany</option>
      <option {% if country == "grc" %} selected {% else %} value="{{ url }}grc/" {% endif %}>Greece</option>
      <option {% if country == "hun" %} selected {% else %} value="{{ url }}hun/" {% endif %}>Hungary</option>
      <option {% if country == "isl" %} selected {% else %} value="{{ url }}isl/" {% endif %}>Iceland</option>
      <option {% if country == "irl" %} selected {% else %} value="{{ url }}irl/" {% endif %}>Ireland</option>
      <option {% if country == "isr" %} selected {% else %} value="{{ url }}isr/" {% endif %}>Israel</option>
      <option {% if country == "ita" %} selected {% else %} value="{{ url }}ita/" {% endif %}>Italy</option>
      <option {% if country == "jpn" %} selected {% else %} value="{{ url }}jpn/" {% endif %}>Japan</option>
      <option {% if country == "lva" %} selected {% else %} value="{{ url }}lva/" {% endif %}>Latvia</option>
      <option {% if country == "ltu" %} selected {% else %} value="{{ url }}ltu/" {% endif %}>Lithuania</option>
      <option {% if country == "lux" %} selected {% else %} value="{{ url }}lux/" {% endif %}>Luxembourg</option>
      <option {% if country == "mlt" %} selected {% else %} value="{{ url }}mlt/" {% endif %}>Malta</option>
      <option {% if country == "nld" %} selected {% else %} value="{{ url }}nld/" {% endif %}>Netherlands</option>
      <option {% if country == "nzl" %} selected {% else %} value="{{ url }}nzl/" {% endif %}>New Zealand</option>
      <option {% if country == "nor" %} selected {% else %} value="{{ url }}nor/" {% endif %}>Norway</option>
      <option {% if country == "pol" %} selected {% else %} value="{{ url }}pol/" {% endif %}>Poland</option>
      <option {% if country == "prt" %} selected {% else %} value="{{ url }}prt/" {% endif %}>Portugal</option>
      <option {% if country == "rou" %} selected {% else %} value="{{ url }}rou/" {% endif %}>Romania</option>
      <option {% if country == "svk" %} selected {% else %} value="{{ url }}svk/" {% endif %}>Slovakia</option>
      <option {% if country == "svn" %} selected {% else %} value="{{ url }}svn/" {% endif %}>Slovenia</option>
      <option {% if country == "esp" %} selected {% else %} value="{{ url }}esp/" {% endif %}>Spain</option>
      <option {% if country == "swe" %} selected {% else %} value="{{ url }}swe/" {% endif %}>Sweden</option>
      <option {% if country == "che" %} selected {% else %} value="{{ url }}che/" {% endif %}>Switzerland</option>
      <option {% if country == "tur" %} selected {% else %} value="{{ url }}tur/" {% endif %}>Turkey</option>
      <option {% if country == "gbr" %} selected {% else %} value="{{ url }}gbr/" {% endif %}>United Kingdom</option>
    </select>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'parties:list' country=country %}">
      <i class="bi bi-people"></i> · Parties
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'elections:list' country=country %}">
      <i class="bi bi-box-seam"></i> · Elections
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'cabinets:list' country=country %}">
      <i class="bi bi-briefcase"></i> · Cabinets
    </a>
  </li>
  <li>
    <a class="nav-link" href="{% url 'docs:index' %}#{{ country }}">
      <i
        class="bi bi-layout-text-sidebar-reverse"
        style="font-size: 0.85rem"
      >
      </i>
    </a>
  </li>
</ul>

<hr />

app/templates/data/cabinet-list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {{ country.name_short|title }} // cabinets
{% endblock %}

{% block content %}

  {% include 'data/_include_form-select-country.html' with country=country.slug url='/data/cabinets/' %}

  <h1>
    {{ country.flag }} · Cabinets
  </h1>

  <table class="table table-striped caption-top">

    <caption>
      List of cabinets in {{ country.name }}
    </caption>

    <thead>
      <tr>
        <th scope="col" class="d-none d-md-table-cell">ID</th>
        <th scope="col">Date</th>
        <th scope="col">
          <span
            data-bs-toggle="tooltip"
            data-bs-placement="top"
            title="Caretaker"
          >
            #
          </span>
        </th>
        <th scope="col">Name</th>
        <th scope="col" class="d-none d-md-table-cell">
          <i class="bi bi-people"></i> · Parties
        </th>
        <th scope="col" style="text-align: center">
          {% url 'admin:cabinets_cabinet_add' as admin_url %}
          {% include '_includes/admin.html' with url=admin_url icon='plus-circle' k='?country=' v=country.id %}
        </th>
      </tr>
    </thead>

    <tbody>
      {% for cabinet in cabinet_list %}
        <tr>
          <td class="d-none d-md-table-cell">
            <small>{{ cabinet.id }}</small>
          </td>
          <td>
            <a href="{{ cabinet.get_absolute_url }}">
              {{ cabinet.start_date|date:"Y-m-d" }}
            </a>
          </td>
          <td>
            {% if cabinet.caretaker %}
              <i
                class="bi bi-calendar-range"
                data-bs-toggle="tooltip"
                data-bs-placement="right"
                title="Caretaker"
              >
              </i>
            {% endif %}
          </td>
          <td>{{ cabinet.name }}</td>
          <td class="d-none d-md-table-cell">
            {% for party in cabinet.cabinetparty_set.all %}
              {% spaceless %}
                <a href="{{ party.party.get_absolute_url }}">
                  <small>{{ party.party.name_short }}</small>
                </a>
                {% if party.pm %}
                  <sup>
                    <i
                      class="bi bi-file-person"
                      data-bs-toggle="tooltip"
                      data-bs-placement="right"
                      title="Prime minister"
                    >
                    </i>
                  </sup>
                {% endif %}
                {% if party.defector %}
                  <sup>
                    <i
                      class="bi bi-door-open"
                      data-bs-toggle="tooltip"
                      data-bs-placement="right"
                      title="Defector"
                    >
                    </i>
                  </sup>
                {% endif %}
              {% endspaceless %}
            {% endfor %}
          </td>
          <td style="text-align: center">
            {% url 'admin:cabinets_cabinet_change' cabinet.id as admin_url %}
            {% include '_includes/admin.html' with url=admin_url icon='pencil' %}
          </td>
        </tr>
      {% endfor %}
    </tbody>

  </table>

  {% include '_includes/tooltip-initialize.html' %}

{% endblock %}

app/templates/data/data-index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Data{% endblock %}

{% block content %}
  <h1>Data</h1>

  <h5><i class="bi bi-globe"></i> · Countries</h5>
  <div class="row mb-4">
    {% for country in countries %}
      <div class="col-sm-3">
        {{ country.flag }} ·
        <a href="{% url 'parties:list' country=country.slug %}">
          {{ country.name }}
        </a>
      </div>
    {% empty %}
      <div class="col">No countries added yet.</div>
    {% endfor %}
  </div>

  <h5><i class="bi bi-download"></i> · Tables</h5>
  <div class="row">
    <p>Download data tables in CSV format.</p>
    <div class="col-3">
      <select id="table-select" class="form-select" onchange="location = this.value;">
        <option value="/data/">[ Select table ]</option>
        {% for table in tables %}
          <option value="/data-csv/{{ table }}">{{ table }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
{% endblock %}

app/templates/data/election-list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {{ country.name_short|title }} // elections
{% endblock %}

{% block content %}
  {% include 'data/_include_form-select-country.html' with country=country.slug url='/data/elections/' %}

  <h1>{{ country.flag }} · Elections</h1>

  <table class="table table-striped caption-top">
    <caption>List of elections in {{ country.name }}</caption>

    <thead>
      <tr>
        <th scope="col" class="d-none d-md-table-cell">ID</th>
        <th scope="col">Date</th>
        <th scope="col">
          <span
            data-bs-toggle="tooltip"
            data-bs-placement="top"
            title="Early"
          >
            #
          </span>
        </th>
        <th scope="col">
          <span
            data-bs-toggle="tooltip"
            data-bs-placement="top"
            title="National / European"
          >
            #
          </span>
        </th>
        <th scope="col" class="d-none d-md-table-cell">Seats</th>
        <th scope="col" class="d-none d-md-table-cell">
          <i class="bi bi-people"></i> · Parties
        </th>
        <th scope="col" style="text-align: center">
          {% url 'admin:elections_election_add' as admin_url %}
          {% include '_includes/admin.html' with url=admin_url icon='plus-circle' k='?country=' v=country.id %}
        </th>
      </tr>
    </thead>

    <tbody>
      {% for election in election_list %}
        <tr>
          <td class="d-none d-md-table-cell">
            <small>{{ election.id }}</small>
          </td>
          <td>
            <a href="{{ election.get_absolute_url }}">
              {{ election.date|date:'Y-m-d' }}
            </a>
          </td>
          <td>
            {% if election.early %}
              <i
                class="bi bi-lightning"
                data-bs-toggle="tooltip"
                data-bs-placement="right"
                title="Early election"
              >
              </i>
            {% endif %}
          </td>
          <td>
            {% if election.type.short == 'ep' %}
              <i
                class="bi bi-globe"
                data-bs-toggle="tooltip"
                data-bs-placement="right"
                title="European election"
              >
              </i>
            {% else %}
              <i
                class="bi bi-pin-map"
                data-bs-toggle="tooltip"
                data-bs-placement="right"
                title="National election"
              >
              </i>
            {% endif %}
          </td>
          <td class="d-none d-md-table-cell">{{ election.seats_total }}</td>
          <td class="d-none d-md-table-cell">
            {% for result in election.electionresult_set.all %}
              {% if result.seats %}
                <a href="{{ result.party.get_absolute_url }}">
                  <small>{{ result.party.name_short }}</small></a>
              {% endif %}
            {% endfor %}
          </td>
          <td style="text-align: center">
            {% url 'admin:elections_election_change' election.id as admin_url %}
            {% include '_includes/admin.html' with url=admin_url icon='pencil' %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% include '_includes/tooltip-initialize.html' %}
{% endblock %}

app/templates/data/party-detail_change.html
{% load format_data %}

<h6>
  Party (name) changes
  {% url 'admin:parties_partynamechange_add' as admin_url %}
  {% include '_includes/admin.html' with url=admin_url icon='plus-circle' k='?party=' v=party.id middot=True %}
</h6>
<ul class="list-unstyled">
  {% for change in party.partynamechange_set.all %}
    <li>
      {{ change.date|ymd_remove_07_01 }} ·
      {{ change.name_short }} · {{ change.name }} ({{ change.name_english }})
      {% url 'admin:parties_partynamechange_change' change.id as admin_url %}
      {% include '_includes/admin.html' with url=admin_url icon='pencil' middot=True %}
    </li>
  {% empty %}
    <li>
      <i>none</i>
    </li>
  {% endfor %}
</ul>

<h6>
  Predecessor
  {% url 'admin:parties_partychange_add' as admin_url %}
  {% include '_includes/admin.html' with url=admin_url icon='plus-circle' k='?party_new=' v=party.id middot=True %}
</h6>
<ul class="list-unstyled">
  {% for change in party.partychange_new_set.all %}
    <li>
      {{ change.date|ymd_remove_07_01 }} ·
      <a href="{% url 'parties:detail' change.party.country.name_short|lower change.party.id %}">
        {{ change.party.name_short }}</a>
      {% url 'admin:parties_partychange_change' change.id as admin_url %}
      {% include '_includes/admin.html' with url=admin_url icon='pencil' middot=True %}
    </li>
  {% empty %}
    <li>
      <i>none</i>
    </li>
  {% endfor %}
</ul>

<h6>
  Successor{% url 'admin:parties_partychange_add' as admin_url %}
  {% include '_includes/admin.html' with url=admin_url icon='plus-circle' k='?party=' v=party.id middot=True %}
</h6>
<ul class="list-unstyled">
  {% for change in party.partychange_set.all %}
    <li>
      {{ change.date|ymd_remove_07_01 }} ·
      <a href="{% url 'parties:detail' change.party_new.country.name_short|lower change.party_new.id %}">
        {{ change.party_new.name_short }}</a>
      {% url 'admin:parties_partychange_change' change.id as admin_url %}
      {% include '_includes/admin.html' with url=admin_url icon='pencil' middot=True %}
    </li>
  {% empty %}
    <li>
      <i>none</i>
    </li>
  {% endfor %}
</ul>