app/apps/docs/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = "docs"

urlpatterns = [
    path(
        "codebook/",
        views.codebook_view,
        name="codebook",
    ),
    path(
        "codebook-markdown/",
        views.codebook_markdown_view,
        name="codebook_markdown",
    ),
    path(
        "news/",
        views.NewsListView.as_view(),
        name="news",
    ),
    path(
        "",
        RedirectView.as_view(pattern_name="docs:codebook"),
        name="index",
    ),
]

app/apps/pages/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "page"

urlpatterns = [
    path("robots.txt", views.RobotsView.as_view(), name="robots"),
    path("login-parlgov", views.UserLoginView.as_view(), name="login"),
    path("logout-parlgov", LogoutView.as_view(), name="logout"),
    path("", views.home_view, name="home"),
]

app/apps/urls.py
"""URL Configuration.

The `urlpatterns` list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/stable/topics/http/urls/
"""

from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from .base import views as views_base
from .data.core import views as views_core
from .views_data import views as views_data

urlpatterns = [
    # Data urls
    path("data/parties/", include("apps.data.parties.urls")),
    path("data/elections/", include("apps.data.elections.urls")),
    path("data/cabinets/", include("apps.data.cabinets.urls")),
    path("data/", views_core.data_index_view, name="country_list"),
    # CSV tables
    path("data-csv/<slug:db_table>/", views_data.csv_view, name="data_csv"),
    # Documentation urls
    path("docs/", include("apps.docs.urls")),
    # API urls
    path("api/v1/", include("apps.api.urls")),
    # path("api-auth/", include("rest_framework.urls")),
    # Page urls
    path("", include("apps.pages.urls")),
    # Misc urls
    path("clear-cache", views_base.clear_cache, name="clear_cache"),
    # Admin urls
    path("admin-parlgov/doc/", include("django.contrib.admindocs.urls")),
    path("admin-parlgov/", admin.site.urls),
]

if settings.DEBUG:  # pragma: no cover
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

app/apps/base/models.py
"""Base models for all apps in the project.

'description', 'comment', 'data_json' fields are used in some models.
No 'DataModel' base model with these fields is used to keep columns and fields
ordered in the database and the Django admin.
"""

from django.db import models
from django.utils import timezone

markdown_help_text = "use Markdown markup language to structure the text"

description_help_text = "information about the observation"
comment_help_text = "comments about the coding of this observation"
data_json_help_text = """additional data saved as key-value pairs in JSON format
                         — use "{}" for empty json fields"""


class BaseModel(models.Model):
    """Base model with default fields 'created_at' and 'updated_at'."""

    created_at = models.DateTimeField(
        db_index=True, default=timezone.now, editable=False
    )
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        abstract = True

app/apps/base/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.core.cache import cache
from django.shortcuts import redirect


@staff_member_required
def clear_cache(request):
    """Clear cached Django page content."""
    cache.clear()
    return redirect("page:home")

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS/JS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}" />
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <title>ParlGov ·{% block title %} default {% endblock %}</title>

    <link
      rel="icon"
      href="{% static 'images/parlgov-favicon.png' %}"
      type="image/png"
    />
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'page:home' %}">
          <img src="{% static 'images/parlgov-logo.svg' %}" />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link link-dark" href="{% url 'country_list' %}">
                <i class="bi bi-table" style="font-size: 0.8rem"></i>
                · Data
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-dark" href="{% url 'docs:index' %}">
                <i
                  class="bi bi-layout-text-sidebar-reverse"
                  style="font-size: 0.85rem"
                >
                </i>
                · Docs
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-dark" href="{% url 'api:api-root' %}">
                <i class="bi bi-code-square" style="font-size: 0.8rem">
                </i>
                · API
              </a>
            </li>
          </ul>
          <ul class="navbar-nav">
            {% if user.is_staff %}
              <li class="nav-item">
                {% include '_includes/clear-cache-modal.html' %}
              </li>
            {% endif %}
            <li class="nav-item">
              {% if user.is_authenticated %}
                <a class="nav-link link-dark" href="{% url 'admin:index' %}">
                  <i class="bi bi-pencil-square"></i>
                </a>
              {% endif %}
            </li>
            <li class="nav-item">
              {% if user.is_authenticated %}
                <a class="nav-link link-dark" href="{% url 'page:logout' %}">
                  <i class="bi bi-box-arrow-right"></i>
                </a>
              {% else %}
                <a class="nav-link link-dark" href="{% url 'page:login' %}">
                  <i class="bi bi-box-arrow-in-right"></i>
                </a>
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <main class="container">
      <div class="alert alert-dark" role="alert">
        <em>Minimal</em> version of ParlGov site — see
        <a href="https://parlgov.org/" class="alert-link">parlgov.org</a>
      </div>
      {% block content %}
        <p>Default content (...)</p>
      {% endblock %}
    </main>
  </body>
</html>